### ISSUE TITLE
django-csv-export-view 2.0.0 with Django 4.2

### ISSUE THREAD

**Issue by tomamihaiadrian** [benkonrath/django-csv-export-view#22]
Hey, I'm trying to use the package from pypi with Django 4.2 and I get the "force_text" import issue.
ImportError: cannot import name 'force_text' from 'django.utils.encoding'
I saw that you fixed that here, is there a new release planned with that change?

**Comment by benkonrath** [comment]
I will make a release soon. Thanks for letting me know.

**Comment by benkonrath** [comment]
Did you close the issue because you got it to work? I just looked... 2.0.0 should work with Django 4.2.

**Comment by benkonrath** [comment]
No worries. I'm happy to hear it's working for you. :-)
